# Generated by Django 5.2 on 2025-04-10 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_autor_fecha_nacimiento_autor_nacionalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
